# The name of the workflow
name: SonarCloud

# Defines when the action should run
on:
  # Triggers the workflow on push events to the main branch
  push:
    branches:
      - main

  # Also triggers the workflow on pull request events
  pull_request:
    types: [opened, synchronize, reopened]

# A workflow run is made up of one or more jobs
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build and analyze
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for better analysis relevancy

      # Sets up a JDK 17 environment for the job with the 'zulu' distribution
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu' # Alternative distributions are available

      # Caches SonarCloud packages
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      # Caches Gradle packages
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      # Grants execute permission for gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x ./demo/gradlew

      # Builds and analyzes the code
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        working-directory: ./demo
        run: ./gradlew build sonar --info -x test
